blank_issues_enabled: false
contact_links:
  - name: Einstein For Developers
    url: https://trailhead.salesforce.com/trailblazer-community/groups/0F94V000000oRJsSAM?tab=discussion&sort=LAST_MODIFIED_DATE_DESC
    about: Please ask and answer questions here.
